version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Docker/dockerfile/app.Dockerfile
    image: wa:1.0
    container_name: app
    restart: unless-stopped
    tty: true
    env_file: .env
    networks:
      - wagw-prod

  web_server:
    build:
      context: ./
      dockerfile: Docker/dockerfile/web_server.Dockerfile
    image: ws_wa:1.0
    container_name: web_server
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    depends_on:
      - app
    networks:
      - wagw-prod


#Docker Networks
networks:
  wagw-prod:
    driver: bridge
